// Propriété, droits d'auteur et version -- même principe que TrajetVE, MeteoAI, Vallet et Scanix.

export const PROPRIETAIRE = "Jean-Luc RIO";
export const ANNEE = 2026;
export const VERSION = 6;
export const VERSION_TEXTE = "Version 6 : correction d'un vrai blocage -- la confirmation \"EFFACER\" (pour remettre le coffre à zéro) était sensible à la casse sans le dire, et ne faisait silencieusement rien si le clavier du téléphone avait mis une majuscule différente. Version 5 :les champs « nouveau mot de passe » (création, changement) ne peuvent plus être remplis automatiquement par un gestionnaire de mots de passe -- ce risque a provoqué un blocage réel -- avec un bouton pour vérifier à l'œil ce qui a été tapé. Version 4 :le code PIN (et son état actuel) est maintenant visible et accessible directement dans Réglages, plus facile à trouver pour un coffre déjà créé. Version 3 : code PIN optionnel à 6 chiffres, requis en plus du mot de passe maître à chaque déverrouillage (combiné cryptographiquement, pas juste vérifié à côté). Version 2 :compatibilité renforcée avec les gestionnaires de mots de passe (Proton Pass et autres) pour remplir le mot de passe maître, et le champ de mot de passe d'une entrée n'est plus proposé par erreur à l'enregistrement du navigateur. Version 1 : coffre de notes chiffré (Argon2id + AES-256-GCM), générateur de mots de passe, verrouillage automatique, lien de sauvegarde chiffré";

export const MENTION_COURTE = `© ${ANNEE} ${PROPRIETAIRE} — Tous droits réservés`;

export const MENTION_LEGALE = `Cette application, son code source, sa conception, ses textes et ses graphismes sont la propriété exclusive de ${PROPRIETAIRE}. Toute reproduction, représentation, modification, adaptation, diffusion ou exploitation, totale ou partielle, sans son autorisation écrite préalable est interdite et constitue une contrefaçon (articles L.122-4 et L.335-2 du Code de la propriété intellectuelle). Coffre fonctionne entièrement sur votre appareil : vos notes ne sont jamais envoyées à un serveur, et aucun mot de passe maître oublié ne peut être récupéré par quiconque, y compris l'auteur. La bibliothèque tierce embarquée (hash-wasm, pour Argon2id) reste soumise à sa licence MIT.`;
